### ISSUE TITLE
breakable showybox with figures

### ISSUE THREAD

**Issue by Marmare314** [Pablo-Gonzalez-Calderon/showybox-package#23]
Hey, I wanted to include a predefined style for using showybox in lemmify, but I ran into an issue.

I would expect this box to break into the second column, but it does not.
```typst
#import "@preview/showybox:2.0.0": showybox
#set page(width: 500pt, height: 100pt, margin: 10pt)
#show: columns.with(2)
#show figure: it => showybox(breakable: true, it.body)
#figure(lorem(50))
```

![image](https://github.com/Pablo-Gonzalez-Calderon/showybox-package/assets/49279081/c686f377-ec81-4416-ae11-f072cab939a5)

Using a plain block works fine.
```typst
#set page(width: 500pt, height: 100pt, margin: 10pt)
#show: columns.with(2)
#show figure: it => block(breakable: true, stroke: 1pt, it.body)
#figure(lorem(50))
```

![showybox](https://github.com/Pablo-Gonzalez-Calderon/showybox-package/assets/49279081/1e085f77-372c-4303-a644-dc1d979492e2)

I find this quite confusing since `showybox(breakable: true, lorem(50))` also works fine, so it has to be something about the figure.

**Comment by Pablo-Gonzalez-Calderon** [comment]
Hmmm. It seems strange to me 🤔

However, I've never tried using a `showybox()` inside a ``figure`` before. Maybe there's some outer ``block`` in the showybox (there's, at least, one outer ``block`` outside the showybox, used for aligning and spacing around it) that "stops" the ``breakable`` behaviour if it's placed inside a non-explicit ``breakable`` container --or something like that.

I'm gonna try to fix this during the day.

Thank you for reporting this! 😁

**Comment by Pablo-Gonzalez-Calderon** [comment]
I'm not really glad of how I found the solution, but I just added the ``breakable`` property to any container that could be causing the error, and it worked 😶

To be specific the containers were: outer "align-``block``" (for setting the correct align of the showybox, given by ``align`` option), body's main ``block`` (which contains all the body sections), and each body section's ``block`` (that, as it names says, contains only one section of the body).

Now this code seems to work perfectly --and all the previous code also works fine, so I think this Issue is solved

```typst
#set page(width: 500pt, height: 100pt, margin: 10pt)
#show: columns.with(2)
#show figure: it => showybox(
    title: "Theorem: " + lorem(10),
    breakable: true,
    shadow: (:),
    title-style: (boxed-style:  (:)),
    it.body
)
#figure(lorem(50))
```

![image](https://github.com/Pablo-Gonzalez-Calderon/showybox-package/assets/30756770/80a33052-c255-4cc1-818c-fccbab323d43)

Tell me if this works for you now using the version 2.0.1 locally (as it is not yet published in Typst packages' repo), to mark this as closed
